dubbo:
  registries:
    zk:
      timeout: 10s
      address: zookeeper://127.0.0.1:2181
  protocols:
    dubbo:
      name: dubbo
      port: 20000
  consumer:
    check: false
    references:
      UserProvider:
        registry: zk
        protocol: dubbo
        interface: org.apache.dubbo.UserService
        cluster: failover
        methods:
          - name: GetUser
            retries: 3